#!/bin/bash
#SBATCH --job-name=test              # Название задачи
#SBATCH --error=cpp-%j.err          # Файл для вывода ошибок
#SBATCH --output=cpp-%j.log         # Файл для вывода результатов
#SBATCH --time=02:00:00              # Максимальное время выполнения
#SBATCH --ntasks=4                   # Количество MPI процессов
#SBATCH --ntasks-per-node=4
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=1            # Требуемое кол-во CPU
#SBATCH --ntasks-per-socket=4

#SBATCH --constraint="type_a"   # Предпочтительный тип узлов
#SBATCH -A proj_1466

module load openmpi

mpicxx -O3 -o matmul.out -march=skylake matmul.cpp

echo "2004" | mpirun ./matmul.out 



