#!/bin/bash
#SBATCH --job-name=test              # Название задачи
#SBATCH --error=cpp-%j.err          # Файл для вывода ошибок
#SBATCH --output=cpp-%j.log         # Файл для вывода результатов
#SBATCH --time=02:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=1            # Требуемое кол-во CPU
#SBATCH --constraint="type_a|type_b"   # Предпочтительный тип узлов
#SBATCH -A proj_1466

./main < /home/maantonov_1/hw1/samples/sample_1.txt
./main < /home/maantonov_1/hw1/samples/sample_2.txt
./main < /home/maantonov_1/hw1/samples/sample_3.txt
./main < /home/maantonov_1/hw1/samples/sample_4.txt


